### ISSUE TITLE
SSR: Server side rendering

### ISSUE THREAD

**Issue by darkowic** [developer239/react-apollo-graphql#16]
Hello! 

Awesome boilerplate!

Do you have plans to add support for server-side rendering? I will be happy to help if I have some time soon :)

**Comment by developer239** [comment]
@darkowic Hey :)
thanks for your feedback it is great to see that this repository helps people.

I am currently working on a game bot that uses [electron](https://github.com/electron/electron) and [opencv](https://github.com/justadudewhohacks/opencv4nodejs) and I want to add [neataptic](https://github.com/wagenaartje/neataptic) so that it can learn to play the game itself. I should be done with opencv and electron part this weekend. So it will probably take me at least a month before I get back to this repository again.

- I wanted to update design
- I wanted to add basic authorization

Server-side rendering is a great idea but it is quite hard to do it correctly. Also, it might introduce some complications in the future (when implementing authorization)

However, I welcome any pull requests.

If you want I can add you to collaborators so that you can make SSR branch directly in this repo.

**Comment by developer239** [comment]
@darkowic I just updated the repository. Better libraries. No redux. No bootstrap. Jest unit tests.

However, there is not SSR yet.

**Comment by developer239** [comment]
I am going to close this issue as I am not going to implement SSR in the near future. I would recommend NextJs for SSR applications anyway. This repository is more supposed to show how to set up react application from scratch manually. (without CRA or NEXT)
